### ISSUE TITLE
Список дел

### ISSUE THREAD

**Issue by Phoenix-FG** [NanzeRT/Avali_SK#1]
Сделай уже бл рецепты)))

**Comment by NullzeRT** [comment]
Да.

**Comment by Phoenix-FG** [comment]
Да это сделал или да - сделаю?)))

**Comment by NullzeRT** [comment]
Да

**Comment by Phoenix-FG** [comment]
Пока я буду заниматься уже существующими рецептами, станками, текстурами (если будет надо) и возможно семенами, ты должен сделать рецепты энергомодулей, исследования (желательно так, чтобы ванильно у Авали были исследованы пояса терморегуляции), патроны.
